rrsite/resumeranker/urls.py
from django.urls import path

from . import views


app_name="resumeranker"

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.send_files, name="uploads"),
    path('keywords/', views.send_keywords, name="keywords"),
    path('reset/', views.reset, name="reset")
]

rrsite/rrsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resumeranker.urls', namespace="resumeranker")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rrsite/resumeranker/models.py
from django.db import models
# Create your models here.

class myUploadFile(models.Model):
    myfiles = models.FileField(upload_to="")

class Data(models.Model):
    text = models.TextField()
    name = models.CharField(max_length=64, null=True)
    collegeName = models.CharField(max_length=100, null=True) 
    degree = models.CharField(max_length=200, null=True)
    graduationYear = models.CharField(max_length=200, null=True)
    yearsOfExperience = models.CharField(max_length=200, null=True)
    companiesWorkedAt = models.CharField(max_length=200, null=True)
    designation = models.CharField(max_length=200, null=True)
    skills = models.TextField(max_length=255, null=True)
    Location = models.TextField(max_length=200, null=True)
    emailAddress = models.EmailField(null=True)

rrsite/resumeranker/views.py
from django.shortcuts import render, HttpResponse
from .models import * 
from .conversion import extract_text_from_pdf, extract_text_from_doc
from .nlp import ner
from .ranking import rank
from django.shortcuts import get_object_or_404

# Create your views here
def index(request):      
    return render(request, "resumeranker/index.html",{
        "part": "part1"
    })

def send_files(request):
    if request.method=="POST":
        myfile = request.FILES.getlist("files")
        for f in myfile:
            myUploadFile(myfiles=f).save()
            current_file=None
            current_file = myUploadFile.objects.all().order_by('-id')[0]
            txt=None
            txt = convert_file_to_txt(current_file)
            if txt is not None:
                dict=None
                dict = ner(txt)
                if dict is not None:
                    Data(text=txt, name=dict["Name"], collegeName=dict["College Name"],degree=dict["Degree"],
                        graduationYear=dict["Graduation Year"],yearsOfExperience=dict["Years of Experience"],
                        companiesWorkedAt=dict["Companies worked at"],designation=dict["Designation"],skills=dict["Skills"],
                        Location=dict["Location"],emailAddress=dict["Email Address"]
                    ).save()
        return render(request, "resumeranker/index.html",{
            "part": "part2"
        }) 

    return render(request, "resumeranker/index.html",{
            "part": "part1"
        })
    

def convert_file_to_txt(current_file):
    extractedtext=None
    current_file_extension = current_file.myfiles.path.split(".")[1].lower()
    if current_file_extension == "pdf":
        extractedtext = extract_text_from_pdf(current_file.myfiles.path)
    elif current_file_extension == ".doc" or current_file_extension == "docx":
        extractedtext = extract_text_from_doc(current_file.myfiles.path)
    return extractedtext


def send_keywords(request):
    if request.method=="POST":
        keywords = request.POST["keywords"]
        data = rank(keywords, Data.objects.all())
        rank_data=[]
        for d in data:
            rank_data.append(get_object_or_404(Data, id = d))
        return render(request, "resumeranker/index.html",{
            "data": Data.objects.all(),
            "rank": rank_data,
            "part": "part3"
        }) 

    return render(request, "resumeranker/index.html",{
            "part": "part2"
        })

def reset(request):
    ids = Data.objects.all().values_list('id', flat=True)
    for i in ids:
        file_obj = get_object_or_404(myUploadFile, id = i)
        file_obj.delete()
        data_obj = get_object_or_404(Data, id = i) 
        data_obj.delete()

    return index(request) 

rrsite/resumeranker/templates/resumeranker/index.html
{% extends "resumeranker/template.html" %}
{% load static%}
{% block head %}
    <link rel="stylesheet" href="{% static '/resumeranker/styles.css' %}">
{% endblock %}
{% block content %}
    <main class="rr-container">
        <div>

            <div class="rr-container_text">
                <h1 class="rr-container_text-title">
                    Resume Parser & Ranker
                </h1>
                <h3 class="rr-container_text-subtitle">
                    Parsing using spaCy NER & TF-IDF Algorithm for Ranking  
                </h3>
            </div>
            
            <div>
                <!-- FILES UPLOAD -->
                <div class="rr-container_content {% if part == 'part1' %}active{% endif %}">
                    <form method="POST" enctype="multipart/form-data" action="{% url 'resumeranker:uploads' %}">
                        <div class="rr-container_content-upload">
                            <label for="files">Drag & Drop all résumés here (Max. 20 résumés)</label>
                            <input type="file" id="files" name="files" multiple accept=".pdf, .docx, .doc" required>
                        </div>
                        {% csrf_token %}    
                        <input type="submit" value="Parse Résumés" class="btn-parse">
                    </form>    
                    
                </div>
                <!-- KEYWORDS SENDING -->
                <div class="rr-container_content {% if part == 'part2' %}active{% endif %}">
                    <form method="POST" enctype="multipart/form-data" action="{% url 'resumeranker:keywords' %}">
                        <div class="rr-container_content-upload">
                            <label for="keywords">Enter Keywords: </label>
                            <input type="text" id="keywords" name="keywords" required placeholder="HTML, CSS, JS, NLP, python...">
                        </div>
                        {% csrf_token %}    
                        <input type="submit" value="Rank Résumés" class="btn-parse">
                    </form>
                </div>
                <div class="rr-container_content {% if part == 'part3' %}active{% endif %}">
                    <div class="rr-container_content-upload">
                        {% if rank %}
                            {% for d in rank %}
                                <p style="text-align: start;">{{d.id}} ------> {{d.name}}
                                    <br>
                                    {{d.designation}} || {{d.skills}} || {{d.Location}} 
                                </p>
                                <hr>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <a class="btn-parse" href="{% url 'resumeranker:reset' %}">Reset</a>
                </div>
            </div>

        </div>
        
    </main>
{% endblock %}

rrsite/resumeranker/templates/resumeranker/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Resume Parser & Ranker</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        {% block head %}

        {% endblock %}
    </head>
    <body>
            {% block content %}

            {% endblock %}
            <script src="{% static '/resumeranker/main.js' %}"></script>
    </body>
    <script>
        $(document).ready(function() {
            {% block jquery %}{% endblock %}
        })
    </script>
</html>